### ISSUE TITLE
"Flux" is a rather confusing name. 

### ISSUE THREAD

**Issue by justgage** [yang-wei/elmflux#14]
Although It's probably to late to change now, I do find this name very confusing to find because it conflicts with Facebook's Flux as you can see by a [google search](https://www.google.com/search?q=elm+flux&oq=elm+flux&aqs=chrome.0.69i59j69i60l3j69i59j69i60.1159j0j1&client=ubuntu&sourceid=chrome&es_sm=93&ie=UTF-8#safe=active&pws=0&q=elmlang+flux).

I think Elm marbles or something like that might make more sense. That's just my two cents.

**Comment by yang-wei** [comment]
thanks for the input but I think because signal is like flux, they are flowing one way so I chose this.
